[package]
name = "spiral-give-me-money"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldk-node = { path = "../ldk-node"}
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
